name: Update Token Information

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次

jobs:
  update_tokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run tokens.js
      run: node tokens.js
    - name: Commit and push if changes
      run: |
        # git config --global user.email "you@example.com"
        # git config --global user.name "Your Name"
        # git add -A
        # git commit -m "Updated token information" -a || echo "No changes to commit"
        # git push